[versions]
loom = "1.17-SNAPSHOT"
fletchingTable = "0.1.0-alpha.22"
ksp = "2.3.11"
kotlin = "2.4.10"

devauth = "1.2.2"
classgraph = "4.8.184"
autoupdate = "1.3.1"
kommand = "1.0.1"
rck = "4.0.0-beta.1"

fabric-loader = "0.19.3"
fabric-language-kotlin = "1.13.13+kotlin.2.4.10"

fabric-api-26-1 = "0.155.2+26.1.2"
fabric-api-26-2 = "0.158.0+26.2"

modmenu-26-1 = "3rsoV1bk"
modmenu-26-2 = "njXb639R"

rc-26-1 = "4.0.0-beta.2"
rc-26-2 = "5.0.0"

snowbird-26-1 = "016+26.1"
snowbird-26-2 = "016+26.2"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-language-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-language-kotlin" }

devauth = { module = "me.djtheredstoner:DevAuth-fabric", version.ref = "devauth" }
autoupdate = { module = "moe.nea:libautoupdate", version.ref = "autoupdate" }
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
kommand = { module = "foo.starred:kommand", version.ref = "kommand" }

fabric-api-26-1 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api-26-1" }
fabric-api-26-2 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api-26-2" }

modmenu-26-1 = { module = "maven.modrinth:modmenu", version.ref = "modmenu-26-1" }
modmenu-26-2 = { module = "maven.modrinth:modmenu", version.ref = "modmenu-26-2" }

rc-26-1 = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-26.1-rc-1", version.ref = "rc-26-1" }
rc-26-2 = { module = "com.teamresourceful.resourcefulconfig:resourcefulconfig-fabric-26.2", version.ref = "rc-26-2" }

rck-26-1 = { module = "com.teamresourceful.resourcefulconfigkt:resourcefulconfigkt-26.1-rc-1", version.ref = "rck" }
rck-26-2 = { module = "com.teamresourceful.resourcefulconfigkt:resourcefulconfigkt-26.1-rc-1", version.ref = "rck" }

snowbird-26-1 = { module = "foo.starred:snowbird", version.ref = "snowbird-26-1" }
snowbird-26-2 = { module = "foo.starred:snowbird", version.ref = "snowbird-26-2" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
fletchingTable = { id = "dev.kikugie.fletching-table.fabric", version.ref = "fletchingTable" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
